plugins: 
 - fluent-plugin-opensearch

fileConfigs:
  04_outputs.conf: |-
    <label @OUTPUT>
      <match ** >
        @type opensearch
        host vpc-opensearch-stage-woesdamvqbli5siagd7guw7ubi.us-west-2.es.amazonaws.com
        port 443
        ssl_verify false
        logstash_format true
        ssl_version TLSv1_2
        logstash_prefix fluentd
        include_timestamp true
        scheme https
      </match>
    </label>
